config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'

  resources :articles do
    resources :comments, only: [:new, :create]
    resource :like, only: [:create, :destroy]
  end
  resource :profile, only: [:show, :edit, :update]
  resources :favorites, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  has_one_attached :eyecatch

  validates :title, presence: true
  validates :title, length: {minimum: 2, maximum: 100}
  validates :title, format: {with: /\A(?!\@)/}

  validates :content, presence: true
  validates :content, length: {minimum: 10}
  validates :content, uniqueness: true

  validate :validate_title_and_content_length

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def auther_name
    user.display_name
  end

  def like_count
    likes.count
  end

  private
  def validate_title_and_content_length
    char_count = self.title.length + self.content.length
    errors.add(:content, '100文字以上で！') unless char_count > 100
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint           not null
#
# Indexes
#
#  index_comments_on_article_id  (article_id)
#
class Comment < ApplicationRecord
  belongs_to :article
  validates :content, presence: true
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_likes_on_article_id  (article_id)
#  index_likes_on_user_id     (user_id)
#
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: {male: 0, female: 1, other: 3}
  belongs_to :user
  has_one_attached :avatar

  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday
    
    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :facorite_articles, through: :likes, source: :article
  has_one :profile, dependent: :destroy

  delegate :birthday, :gender, :age, to: :profile, allow_nil: true

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def has_liked?(article)
    likes.exists?(article_id: article.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  

  def set_article
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to article_path(@article), notice: '保存できたよ'
    else
      flash.now[:error] = '保存できませんでした'
      # NOTE: Rails 7ではstatus: :unprocessable_entityを入れる必要がある
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path, notice: '削除に成功しました',status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :eyecatch)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    article = Article.find(params[:article_id])
    @comment = article.comments.build
  end

  def create
    article = Article.find(params[:article_id])
    @comment = article.comments.build(comment_params)
    if @comment.save
      redirect_to article_path(article), notice: 'コメントを追加できたよ'
    else
      flash.now[:error] = 'コメントを追加できませんでした'
      # NOTE: Rails 7ではstatus: :unprocessable_entityを入れる必要がある
      render :new, status: :unprocessable_entity
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.facorite_articles
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    article = Article.find(params[:article_id])
    article.likes.create!(user_id: current_user.id)
    redirect_to article_path(article)
  end

  def destroy
    article = Article.find(params[:article_id])
    like = article.likes.find_by!(user_id: current_user.id)
    like.destroy!
    redirect_to article_path(article)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%= form_with(model: article, local: true) do |f| %>
    <div>
      <%= f.label :eyecatch, 'アイキャッチ' %>
    </div>
    <div>
      <%= f.file_field :eyecatch %>
    </div>
    <div>
      <%= f.label :title, 'タイトル' %>
    </div>
    <div>
      <%= f.text_field :title, class: 'title' %>
    </div>
    <div>
      <%= f.label :content, '内容' %>
    </div>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit '保存', class: 'btn-primary' %>
  <% end %>
</div>

app/views/articles/_tabs.html.erb
<div class="tabs">
  <div class="tabs_item active">
    新着記事一覧
  </div>
  <div class="tabs_item">
    タイムライン
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>HOME</h1>

<div class="container">
  <%= render 'tabs' %>

  <% @articles.each do |article| %>
    <%= render 'commons/article', article: article %>
  <% end %>
  <%= link_to new_article_path do %>
    <div class="float_btn">
      <i class="fa fa-plus"></i>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="article">
  <% if @article.eyecatch.attached? %>
    <%= image_tag @article.eyecatch, class: 'article_image' %>
  <% end %>
  <h1 class="article_title"><%= @article.title %></h1>
  <div class="article_detail">
    <%= image_tag @article.user.avatar_image %>
    <div>
      <p><%= @article.auther_name %></p> 
      <p><%= @article.display_created_at %></p>
    </div>
    <div class="article_detail_actions">
    <% if user_signed_in? && current_user.has_written?(@article) %>
      <div class="dropdown">
        <%= image_tag 'actions.svg', class: 'dropbtn' %>
          <div class="dropdown-content mini">
            <%= link_to '編集する', edit_article_path(@article) %>
            <%= link_to '削除する', article_path(@article), data:{turbo_method:'delete', turbo_confirm: '本当に削除してもよろしいですか？'} %>
          </div>
      </div>
    <% end %>
    </div>
  </div>
  <div class="article_content">
    <%= @article.content %>
  </div>
  <% if user_signed_in? %>
    <% if current_user.has_liked?(@article) %> 
      <div class="article_heart">
        <%= link_to image_tag('heart-active.svg'), article_like_path(@article), data: {turbo_method: 'delete'} %>
      </div>
    <% else %>
      <div class="article_heart">
        <%= link_to image_tag('heart.svg'), article_like_path(@article), data: {turbo_method: 'post'} %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="article">
  <h2>コメント一覧</h2>
  <% @comments.each do |comment| %>
    <div class="article_comment"><%= comment.content %></div>
  <% end %>
</div>
<div class="container">
  <%= link_to new_article_comment_path(@article) do %>
    <button class='btn-secondary'>コメントを追加</button>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%= form_with(model: @comment, url: article_comments_path(@comment.article), local: true) do |f| %>
    <div>
      <%= f.label :content, '内容' %>
    </div>
    <div>
      <%= f.text_area :content %>
    </div>
    <%= f.submit '保存', class: 'btn-primary' %>
  <% end %>
</div>

app/views/commons/_article.html.erb
<%= link_to article_path(article) do %>
  <div class="card">
    <% if article.eyecatch.attached? %>
      <div class="card_image">
        <%= image_tag article.eyecatch %>
      </div>
    <% end %>
    <div class="card_content">
      <div class="card_title">
        <%= article.title%>
      </div>
      <div class="card_heart">
        <%= image_tag 'heart.svg' %>
        <span><%= article.like_count %></span>
      </div>
      <div class="card_detail">
        <%= image_tag article.user.avatar_image %>
        <div>
          <p><%= article.auther_name %></p>
          <p><%= article.display_created_at %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/favorites/index.html.erb
<div class="container">
  <h2>お気に入りの記事</h2>
  <% @articles.each do |article| %>
    <%= render 'commons/article', article: article %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDaylyTrial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" crossorigin="anonymous">
  </head>

  <body>
    <header class="header">
      <div class="header_logos">
        <% if !current_page?(root_path) %>
          <%= link_to :back do %>
            <%= image_tag 'back.svg', class: 'header_back' %>
          <% end %>
        <% end %>
        <%= link_to 'BlogApp', root_path %>
      </div>
      <% if user_signed_in? %>
        <div class="dropdown">
          <%= image_tag current_user.avatar_image, class: 'header_avatar dropbtn' %>
          <div class="dropdown-content">
            <%= link_to 'プロフィール', profile_path %>
            <%= link_to 'お気に入り', favorites_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, data:{turbo_method: :delete} %>
          </div>
        </div>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    </header>
    <% if flash.present? %>
      <div class="flash">
        <% flash.each do |key, value| %>
        <div class="flash">
          <div class="<%= key %>"><%= value %></div> 
        </div>
        <% end %> 
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<div class="container">
  <ul>
    <% @profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f| %>
    <div>
      <%= f.label :avatar, 'アバター' %>
    </div>
    <div>
      <%= f.file_field :avatar %>
    </div>
    <div>
      <%= f.label :nickname, 'ハンドルネーム' %>
    </div>
    <div>
      <%= f.text_field :nickname, class: 'text' %>
    </div>
    <div>
      <%= f.label :introduction, '自己紹介' %>
    </div>
    <div>
      <%= f.text_area :introduction %>
    </div>
    <div>
      <%= f.label :gender, '性別' %>
    </div>
    <div>
      <%= f.select :gender, Profile.genders.map {|key, value| [I18n.t("enum.genders.#{key}"),key]},{}, {class: 'text' } %>
    </div>
    <div>
      <%= f.label :birthday, '生年月日' %>
    </div>
    <div>
      <%= f.date_field :birthday, class: 'text' %>
    </div>
    <div>
      <%= f.label :subscribed, '通知を受け取る' %>
    </div>
    <div>
      <%= f.check_box :subscribed %>
    </div>
    <%= f.submit '保存', class: 'btn-primary' %>
  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container profilePage">
  <div class="profilePage_user">
    <div class="profilePage_user_image">
      <%= image_tag current_user.avatar_image %>
    </div>
    <div class="profilePage_user_basicInfo">
      <div class="profilePage_user_name">
        <div class="profilePage_user_displayName">
          <%= "#{current_user.display_name} (#{current_user.age}・#{I18n.t("enum.genders.#{current_user.gender}")}）" %>
        </div>
        <div class="profilePage_user_actionButton">
          <%= link_to 'Edit', edit_profile_path %>
        </div>
      </div>
      <div class="profilePage_user_introduction">
        <%= current_user.profile&.introduction %>
      </div>
    </div>
  </div>
  <% current_user.articles.each do |article| %>
    <%= render 'commons/article', article: article %>
  <% end %>
</div>